CREATE TABLE mail (
  id INTEGER PRIMARY KEY NOT NULL,
  target VARCHAR NOT NULL,
  sender VARCHAR NOT NULL,
  message VARCHAR NOT NULL,
  sent DATETIME NOT NULL,
  private BOOLEAN NOT NULL DEFAULT 'f'
)
